sudo: required
before_install:
  - npm install -g node-gyp
language: node_js
node_js:
  - stable
services:
  - postgresql
before_script:
  - psql -c 'create database box_jumpers_db;' -U postgres
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
env:
  - JWT=12345 CXX=g++-4.8
